build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true

style:
  UtilityClassWithPublicConstructor:
    active: false

  MagicNumber:
    active: false

  WildcardImport:
    active: true

  MaxLineLength:
    active: true
    maxLineLength: 140
    excludePackageStatements: true
    excludeImportStatements: true

  ReturnCount:
    active: false

  ThrowsCount:
    active: false

  NewLineAtEndOfFile:
    active: true

complexity:
  LongMethod:
    active: true
    threshold: 60

  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 8

  TooManyFunctions:
    active: false

formatting:
  active: true
  autoCorrect: true

  MaximumLineLength:
    active: true
    maxLineLength: 140

  NoWildcardImports:
    active: true

  FinalNewline:
    active: true

  NoSemicolons:
    active: true

  Indentation:
    active: true
    indentSize: 4

  SpacingAroundColon:
    active: true

  SpacingAroundComma:
    active: true

  SpacingAroundCurly:
    active: true

  SpacingAroundKeyword:
    active: true

  SpacingAroundOperators:
    active: true

  NoConsecutiveBlankLines:
    active: true

exceptions:
  active: true

  TooGenericExceptionThrown:
    active: false

  TooGenericExceptionCaught:
    active: false

  SwallowedException:
    active: false
