name: CI

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Give execute permission to gradlew
        run: chmod +x gradlew

      - name: Detekt static analysis
        run : ./gradlew detekt

      # ✅ 1. Build
      - name: Build project
        run: ./gradlew clean build

      # ✅ 2. Unit tests
      - name: Run unit tests
        run: ./gradlew test

      - name: Run integration tests
        run: ./gradlew testIntegration

      # ✅ 3. Component tests (Cucumber / REST Assured)
      - name: Run component tests
        run: ./gradlew testComponent

      - name: Run architecture tests
        run: ./gradlew testArchitecture

      # ✅ 4. Génération couverture
      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport

      # ✅ 5. Mutation testing (PIT)
      - name: Run PIT mutation tests
        run: ./gradlew pitest

      # 📦 Test reports
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/test-results/

      # 📦 Coverage reports
      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/

      # 📦 PIT reports
      - name: Upload PIT report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path: build/reports/pitest/
