name: CI

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Give execute permission to gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean build
      - name : test
        run: ./gradlew test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/test-results/

      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/

      - name: Run PIT mutation tests
        run: ./gradlew pitest

      - name: Upload PIT report
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path: build/reports/pitest/